### PR TITLE
Expand pod simulator frontend crash control to all mutable commands

### PR DESCRIPTION
**Pull request by itsmojo**

### CODE REVIEW

**Review by ps2 — CHANGES_REQUESTED** [review]
I added this command specifically to allow testing of uncertain delivery.  To test uncertain delivery, you want to be precise about when it crashes. Crashing on a status command or other commands would while running the test would invalidate the test.  I could see adding another flag to crash on all commands, or to be specific.  But I think we need to keep the ability to restrict the crash to insulin scheduling commands.

What are you trying to accomplish? That might help me offer suggestions.

**Comment by itsmojo** [comment]
Status commands are not mutable and thus there are no changes in behavior for these commands. The changes in this PR were made so that all the uncertain insulin delivery tests will all run exactly as before. Expanding the pod simulator crash support allows for possible additional Loop testing for lost/unconfirmed non-insulin commands which can change pod state (in particular setting & acknowledging alerts).

**Comment by ps2** [comment]
I mean if I'm trying to test uncertain delivery, and set it to crash *after* the bolus command, and Loop runs a status command before my bolus and the pod crashes, then the test is invalidated, and it's hard for me to tell if Loop is doing the right thing.

**Comment by ps2** [comment]
Ok, it'd be pretty rare for one of those other messages (setting/acknowledging alerts) to be sent by Loop while testing. Thanks.

**Comment by ps2** [comment]
Thanks. I think I understand it won't affect testing now. I can't remember; does the UI say this will only crash on the delivery command? If so maybe we should update that as well.

**Comment by itsmojo** [comment]
The UI doesn't display anything about crashing on delivery commands, just the "next command".

Screenshot 2022-12-20 at 5 54 27 PM

With this PR, the pod simulator is actually closer to the "Crash before/after processing next command" button descriptions. If we wanted to be explicit, we could expand these button labels to something like "Crash before/after processing next non-status command".

**Pull request merged**
